# Generated by Django 3.0.11 on 2020-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
