# Generated by Django 3.0.11 on 2020-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_application_applicant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
